<?php include_once("../includes/includes.php");
$remisionid = (int)($_GET['remisionid'] ?? 0);

$db = new FirebirdConnection();
$row = $db->query("
  SELECT FIRST 1 
    RPA.REMISIONPROVARTICULO_ID,
    RPA.REMISIONPROVARTICULO_CANTIDAD,
    RPA.REMISIONPROVARTICULO_TOTAL,
    P.NOMBRE AS NOMBREPROVEEDOR,
    A.NOMBRE AS NOMBRE_ARTICULO,
    /* por compatibilidad si no hubiera totales calculados */
    (SELECT FIRST 1 AP.ARTPRECIO_TOTAL
     FROM AMPAR_CAT_ARTPRECIO AP 
     WHERE AP.ARTPRECIO_ARTICULOID = RPA.REMISIONPROVARTICULO_ARTICULOID
       AND (AP.ARTPRECIO_CLIENTEID = E.EVENTO_CLIENTEID OR AP.ARTPRECIO_CLIENTEID IS NULL)
     ORDER BY CASE WHEN AP.ARTPRECIO_CLIENTEID = E.EVENTO_CLIENTEID THEN 0 ELSE 1 END
    ) AS PRECIO_TOTAL
  FROM AMPAR_HIS_REMISIONESPARTICULOS RPA
  JOIN AMPAR_HIS_REMISIONES R ON R.REMISION_ID = RPA.REMISIONPROVARTICULO_REMISIONID
  JOIN AMPAR_HIS_EVENTOS E     ON E.EVENTO_ID   = R.REMISION_EVENTOID
  JOIN PROVEEDORES P ON P.PROVEEDOR_ID = RPA.REMISIONPROVARTICULO_PROVID
  JOIN ARTICULOS   A ON A.ARTICULO_ID  = RPA.REMISIONPROVARTICULO_ARTICULOID
  WHERE RPA.REMISIONPROVARTICULO_REMISIONID = ?
  ORDER BY RPA.REMISIONPROVARTICULO_ID DESC
", [$remisionid]);
$db->close();
echo json_encode($row ? $row[0] : new stdClass());
?>